import './style.css';
import {TEAMS,normalizeFavorites,favoriteTeams,SERVICE_GROUPS,SERVICE_LABELS} from './preferences.js';
import { createIcons, CalendarDays, MapPin, ArrowUpRight, ChevronLeft, ChevronRight, Bell, BellRing, Radio, Tv, Smartphone, Check, RefreshCw, Settings2, Download, X, Search, ExternalLink, Info, ArrowRight, CircleHelp, WifiOff, Zap } from 'lucide';
import {DEFAULT_SERVICES,STATIONS,slateRange,normalizeScoreboard,mergeVerification,access,mountain,kickoff,localDate,calendar,safeUrl} from './core.js';
import {registerGuideTools} from './agent-tools.js';
const icons={CalendarDays,MapPin,ArrowUpRight,ChevronLeft,ChevronRight,Bell,BellRing,Radio,Tv,Smartphone,Check,RefreshCw,Settings2,Download,X,Search,ExternalLink,Info,ArrowRight,CircleHelp,WifiOff,Zap};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name,cls='')=>`<i data-lucide="${name}" class="${cls}" aria-hidden="true"></i>`;
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{toast('Your browser could not save this preference.');}};
let favorites=normalizeFavorites(read('huddle.favorites',{}));
let services={...DEFAULT_SERVICES,...read('huddle.services',{})},saved=read('huddle.saved',[]),offset=0,filter='all',query='',games=[],dataState='loading',checked=null,api='',loading=false,installPrompt=null,registration=null,sequence=0,verificationError='';
function paintIcons(){createIcons({icons,attrs:{'stroke-width':1.7}});}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),5000);}
function shell(){
 $('#app').innerHTML=`<a href="#guide" class="skip">Skip to games</a><header class="topbar"><a class="brand" href="./" aria-label="Boulder Huddle home"><img class="brandmark" src="./icon.svg" alt=""><span>huddle<span class="brand-dot">.</span></span></a><span class="header-divider"></span><span class="edition">BOULDER EDITION</span><div class="top-right"><span class="location">${icon('map-pin')} Boulder, CO <span class="muted">· Mountain Time</span></span><button id="settings" class="icon-button" aria-label="Settings">${icon('settings-2')}</button><button id="install" class="button small">${icon('download')} Install app</button></div></header>
 <main><div class="intro"><div><div class="eyebrow">YOUR WEEKLY NFL VIEWING GUIDE</div><h1>Football. <span>Sorted.</span></h1><p>Every matchup. Your channels. Zero guesswork.</p></div><button class="button primary" id="alerts">${icon('bell')} Game reminders</button></div>
 <section class="service-strip" aria-label="Your services"><div class="service-label">YOUR LINEUP</div><div id="services"></div><button class="text-button" id="edit-services">Edit ${icon('arrow-up-right')}</button></section>
 <div class="workspace"><div class="main-column"><section id="spotlight"></section><section id="guide" aria-label="Weekly games"><div class="guide-heading"><div><h2>The weekly slate <span id="game-total"></span></h2><p id="week-caption">Loading the upcoming slate…</p></div><div class="week-controls"><button id="prev" class="icon-button" aria-label="Previous week">${icon('chevron-left')}</button><button id="current" class="text-button">This week</button><button id="next" class="icon-button" aria-label="Next week">${icon('chevron-right')}</button></div></div><div class="filters"><div class="segments" role="group" aria-label="Filter games"><button data-filter="all" class="active" aria-pressed="true">All games</button><button data-filter="full" aria-pressed="false">Full game</button><button data-filter="redzone" aria-pressed="false">RedZone</button><button data-filter="saved" aria-pressed="false">Saved</button></div><label class="search">${icon('search')}<input id="search" placeholder="Find a team" aria-label="Find a team"></label></div><div id="freshness" class="freshness" role="status"></div><div id="games" aria-live="polite"><div class="empty">Loading your slate…</div></div></section></div>
 <aside><section class="panel access-key"><div class="eyebrow">KNOW YOUR ACCESS</div><h3>One look. All clear.</h3><div class="key-item"><span class="key-icon green">${icon('tv')}</span><div><strong>Full game</strong><p>Watch live with a service you have.</p></div></div><div class="key-item"><span class="key-icon red">${icon('zap')}</span><div><strong>RedZone only</strong><p>Live look-ins. Not a full broadcast.</p></div></div><div class="key-item"><span class="key-icon blue">${icon('smartphone')}</span><div><strong>Mobile / tablet</strong><p>NFL+ live games. No TV casting.</p></div></div><div class="key-item"><span class="key-icon amber">${icon('circle-help')}</span><div><strong>Extra service / pending</strong><p>Another subscription, or an assignment still to verify.</p></div></div></section>
 <section class="panel"><div class="eyebrow">YOUR LOCAL DIAL</div><h3>Free over the air.</h3><div class="stations">${Object.entries(STATIONS).map(([n,s])=>`<div><span class="network-word">${n}</span><span>${s.split(' · ')[0]}</span><strong>${s.split(' · ')[1]}</strong></div>`).join('')}</div><p class="fine">Denver-market virtual channels. Reception depends on your antenna and location. A network listing does not confirm a local game.</p></section>
 <section class="panel redzone-panel"><span class="tiny-tag">SUNDAY AFTERNOONS</span><h3>Around the league.<br>Without the channel hop.</h3><p>Your NFL+ Premium includes RedZone. Keep it alongside your local game for live scoring opportunities.</p><a href="https://www.nfl.com/plus/" target="_blank" rel="noreferrer">Open NFL+ ${icon('arrow-up-right')}</a></section>
 <section class="source-panel"><h4>${icon('info')} Built for changing schedules</h4><p>Kickoffs refresh on opening and every five minutes. Local assignments and rights are checked separately. Always check again before kickoff.</p><button id="sources" class="text-button">Sources & verification ${icon('arrow-up-right')}</button></section></aside></div>
 <footer><span class="footer-brand">huddle.</span><span>Made for game day in Boulder.</span><span>Independent guide · Not affiliated with the NFL</span></footer></main><dialog id="dialog"><div id="dialog-content"></div></dialog><div id="toast" role="status" class="toast"></div>`;
 $('#settings').onclick=()=>settings();$('#edit-services').onclick=()=>settings();$('#alerts').onclick=()=>reminders();$('#install').onclick=install;$('#sources').onclick=sourcesDialog;
 $('#prev').onclick=()=>changeWeek(-1);$('#next').onclick=()=>changeWeek(1);$('#current').onclick=()=>{offset=0;load();};
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderGames();});
 $('#search').oninput=e=>{query=e.target.value;renderGames();};
 $('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))$('#dialog').close();});
 $('#games').addEventListener('click',gameAction);$('#spotlight').addEventListener('click',gameAction);
 renderServices();paintIcons();
}
function renderServices(){$('#services').innerHTML=Object.entries(SERVICE_LABELS).filter(([key])=>services[key]&&!key.startsWith('tv_')).map(([key,label])=>`<span class="service-chip">${icon('tv')}${esc(label)}<span class="service-check">${icon('check')}</span></span>`).join('')||'<span class="muted">No services selected</span>';paintIcons();}
function teamLogo(t){const url=safeUrl(t.logo);return url?`<img class="team-logo" src="${esc(url)}" alt="" loading="lazy" onerror="this.style.display='none'">`:'';}
function renderSpotlight(){const picks=[...new Set(Object.values(favorites).filter(Boolean).map(t=>games.find(g=>g.state!=='post'&&(g.away.abbr===t||g.home.abbr===t))).filter(Boolean))];if(!picks.length){const next=games.find(g=>g.state!=='post')||games[0];if(next)picks.push(next);}$('#spotlight').innerHTML=picks.map(g=>{const a=access(g,services),chosen=favoriteTeams(g,favorites);return `<article class="spotlight"><div class="spotlight-top"><span class="tiny-tag">${icon(chosen.length?'map-pin':'calendar-days')} ${chosen.length?'YOUR TEAM · '+chosen.join(' + '):'UP NEXT'}</span><span>${esc(mountain(g.date,{weekday:'long'}))} ${icon('arrow-up-right')}</span></div><div class="spotlight-content"><div><div class="spotlight-meta">${esc(g.networks.join(' + '))} <span>·</span> ${esc(kickoff(g))} MT</div><h2>${esc(g.away.short)} <span>at</span><br>${esc(g.home.short)}</h2><p>${esc(g.venue)}</p></div><div class="matchup-logos">${teamLogo(g.away)}<span>VS</span>${teamLogo(g.home)}</div></div><div class="spotlight-bottom"><span>${icon(a.kind==='full'?'tv':'info')} ${esc(a.line)}</span><button data-action="save" data-id="${esc(g.id)}" class="button spotlight-save" aria-pressed="${saved.includes(g.id)}">${icon(saved.includes(g.id)?'check':'bell')} ${saved.includes(g.id)?'Saved':'Save game'}</button></div></article>`;}).join('');paintIcons();}
function gameCard(g){const a=access(g,services);return `<article class="game ${a.kind}" id="game-${esc(g.id)}"><div class="game-time"><strong>${esc(kickoff(g))}</strong><span>MT${g.state==='post'?' · FINAL':g.state==='in'?' · LIVE':''}</span></div><div class="game-main"><div class="matchup">${teamLogo(g.away)}<h3>${esc(g.away.short)} <span>at</span> ${esc(g.home.short)}</h3>${teamLogo(g.home)}${favoriteTeams(g,favorites).map(t=>`<span class="home-tag">${esc(t)}</span>`).join('')}</div><div class="broadcast">${esc(g.networks.join(' / ')||'Broadcaster TBD')}${g.neutral?' <span>·</span> '+esc(g.venue):''}${a.station?' <span>·</span> '+esc(a.station):''}</div><div class="watch-line"><strong>How you can watch</strong><span>${esc(a.line)}</span></div><p class="access-detail">${esc(a.detail)}</p>${g.notes?`<p class="access-detail">${esc(g.notes)}</p>`:''}<div class="game-links"><button data-action="detail" data-id="${esc(g.id)}">${icon('external-link')} Sources & details</button><button data-action="calendar" data-id="${esc(g.id)}">${icon('calendar-days')} Calendar</button></div></div><div class="game-end"><span class="badge ${a.kind}">${icon(a.kind==='full'?'check':a.kind==='mobile'?'smartphone':a.kind==='redzone'?'zap':'circle-help')}${esc(a.label)}</span><button class="icon-button save ${saved.includes(g.id)?'selected':''}" data-action="save" data-id="${esc(g.id)}" aria-label="${saved.includes(g.id)?'Unsave':'Save'} ${esc(g.away.short)} at ${esc(g.home.short)}" aria-pressed="${saved.includes(g.id)}">${icon(saved.includes(g.id)?'bell-ring':'bell')}</button></div></article>`;}
function renderGames(){
 document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===filter);b.setAttribute('aria-pressed',b.dataset.filter===filter);});
 const visible=games.filter(g=>{const a=access(g,services);return (filter==='all'||(filter==='full'&&a.kind==='full')||(filter==='redzone'&&a.redzone)||(filter==='saved'&&saved.includes(g.id)))&&`${g.home.name} ${g.away.name} ${g.home.abbr} ${g.away.abbr}`.toLowerCase().includes(query.toLowerCase());});
 const groups=Object.groupBy(visible,g=>localDate(g.date));$('#games').innerHTML=visible.length?Object.entries(groups).map(([day,items])=>`<section class="day-group"><div class="day-heading"><h3>${esc(mountain(day+'T12:00:00Z',{weekday:'long'}))}<span>${esc(mountain(day+'T12:00:00Z',{month:'short',day:'numeric'}))}</span></h3><span>${items.length} ${items.length===1?'GAME':'GAMES'}</span></div>${items.map(gameCard).join('')}</section>`).join(''):`<div class="empty">${loading?'Finding this week’s games…':games.length?'No games match this view. Try All games or another team.':dataState==='error'?'The schedule could not be loaded. Check your connection and refresh.':'No NFL games are scheduled in this date range.'}</div>`;
 $('#game-total').textContent=games.length;const r=slateRange(new Date(),offset);$('#week-caption').textContent=`${games[0]?.week?'Week '+games[0].week+' · ':''}${mountain(r.start+'T12:00Z',{month:'short',day:'numeric'})} – ${mountain(r.end+'T12:00Z',{month:'short',day:'numeric',year:'numeric'})} · All times Mountain`;
 $('#prev').disabled=offset<=-30;$('#next').disabled=offset>=30;renderFreshness();paintIcons();
}
function renderFreshness(){const pending=games.filter(g=>access(g,services).kind==='pending').length;const state=dataState==='cached'?'Saved schedule · offline or live feed unavailable':dataState==='snapshot'?'Bundled Sep 9 snapshot · not live':dataState==='error'?'Live schedule unavailable':loading?'Refreshing schedule…':`Schedule updated ${checked?mountain(checked,{hour:'numeric',minute:'2-digit'}):'—'} MT`;$('#freshness').innerHTML=`<span>${icon(dataState==='cached'?'wifi-off':'refresh-cw')} ${esc(state)}${pending?` <span class="pending-count">· ${pending} access checks pending</span>`:''}</span><button id="refresh" class="text-button" ${loading?'disabled':''}>Refresh</button>${verificationError?`<p>${esc(verificationError)}</p>`:''}`;$('#refresh').onclick=()=>load();paintIcons();}
async function json(url,options={},timeout=20000){const response=await fetch(url,{...options,signal:AbortSignal.timeout(timeout)});if(!response.ok)throw new Error(`Request failed (${response.status})`);return response.json();}
async function load(){const current=++sequence;loading=true;verificationError='';renderFreshness();const range=slateRange(new Date(),offset),cacheKey='huddle.slate.'+range.start;try{
 const endpoint=`https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?dates=${range.start.replaceAll('-','')}-${range.end.replaceAll('-','')}&limit=100`;
 if(api){try{const preliminary=normalizeScoreboard(await json(endpoint));if(current!==sequence)return;games=preliminary;checked=new Date().toISOString();dataState='live';verificationError='Checking current Denver broadcasts and streaming rights…';renderGames();renderSpotlight();}catch{}}
 const result=api?await json(`${api}/guide?start=${range.start}`,{},195000):{games:normalizeScoreboard(await json(endpoint)),checkedAt:new Date().toISOString()};
 if(current!==sequence)return;games=result.games;checked=result.checkedAt;dataState='live';verificationError=result.verificationMessage||(!api?'Connect the guide service in Settings for live Denver assignment checks and background reminders.':'');write(cacheKey,{games,checked});
 }catch(e){if(current!==sequence)return;const cache=read(cacheKey,null);if(cache){games=cache.games;checked=cache.checked;dataState='cached';}else{try{const snapshot=await json('./snapshot.json');if(snapshot.start===range.start){games=snapshot.games;checked=snapshot.checkedAt;dataState='snapshot';}else{games=[];dataState='error';}}catch{games=[];dataState='error';}}verificationError='Live refresh failed. Previously retrieved listings may have changed; local access is not newly verified.';}
 finally{if(current===sequence){loading=false;renderGames();renderSpotlight();}}
}
function changeWeek(n){offset=Math.max(-30,Math.min(30,offset+n));games=[];renderGames();load();}
function modal(title,body){$('#dialog-content').innerHTML=`<div class="modal-heading"><h2>${esc(title)}</h2><button class="icon-button" id="close-dialog" aria-label="Close">${icon('x')}</button></div>${body}`;$('#close-dialog').onclick=()=>$('#dialog').close();if(!$('#dialog').open)$('#dialog').showModal();paintIcons();}
function settings(){modal('Your game-day setup',`<p class="muted">Boulder / Denver market · Mountain Time</p><h3>Your teams</h3><p class="fine">One team per conference. Your picks feature their next games; local channels stay in the Denver market.</p><div class="team-options">${Object.entries(TEAMS).map(([conference,teams])=>`<label class="field">${conference}<select id="team-${conference}">${conference==='NFC'?'<option value="">Choose an NFC team</option>':''}${Object.entries(teams).map(([abbr,name])=>`<option value="${abbr}" ${favorites[conference]===abbr?'selected':''}>${name}</option>`).join('')}</select></label>`).join('')}</div>${SERVICE_GROUPS.map(group=>`<h3>${group.title}</h3>${group.note?`<p class="fine">${group.note}</p>`:''}<div class="service-options">${Object.entries(group.items).map(([key,label])=>`<label><input type="checkbox" data-service="${key}" ${services[key]?'checked':''}>${label}</label>`).join('')}</div>`).join('')}<p class="fine">Select the plan you have. ESPN Select does not include every ESPN game. Event streams appear only when named by the schedule. International Game Pass does not provide live games in Boulder.</p><details><summary>Connection settings</summary><label class="field">Live guide URL<input id="api-url" type="url" value="${esc(api)}"></label><p class="fine">Your guide refreshes without a paid API key. Preferences stay on this device and sync for enabled reminders.</p></details><button id="save-settings" class="button primary settings-save">Save settings</button>`);$('#save-settings').onclick=async()=>{const value=$('#api-url').value.trim().replace(/\/$/,'');if(value&&!safeUrl(value)){toast('Enter a valid HTTPS service URL.');return;}if(value!==api&&registration&&await registration.pushManager.getSubscription()){toast('Turn off reminders before changing the service URL.');return;}document.querySelectorAll('[data-service]').forEach(i=>services[i.dataset.service]=i.checked);favorites=normalizeFavorites({AFC:$('#team-AFC').value,NFC:$('#team-NFC').value});write('huddle.favorites',favorites);api=value;write('huddle.services',services);write('huddle.api',api);$('#dialog').close();renderServices();renderGames();renderSpotlight();await syncSubscription().catch(()=>toast('Services saved locally; reminder settings could not sync.'));load();};}
async function gameAction(e){const b=e.target.closest('[data-action]');if(!b)return;const g=games.find(g=>g.id===b.dataset.id);if(!g)return;if(b.dataset.action==='save'){saved=saved.includes(g.id)?saved.filter(x=>x!==g.id):[...saved,g.id];write('huddle.saved',saved);renderGames();renderSpotlight();toast(saved.includes(g.id)?'Game saved. Enable Game reminders for kickoff alerts.':'Game removed from saved games.');await syncSubscription().catch(()=>toast('Saved locally. Reminder sync failed; try again in Game reminders.'));}if(b.dataset.action==='calendar'){if(g.timeTbd)return toast('Kickoff time is still TBD. Add it once the time is confirmed.');const url=URL.createObjectURL(new Blob([calendar(g,access(g,services))],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download=`${g.away.abbr}-${g.home.abbr}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(b.dataset.action==='detail'){const a=access(g,services);modal(`${g.away.short} at ${g.home.short}`,`<p>${esc(mountain(g.date,{weekday:'long',month:'long',day:'numeric'}))} · ${esc(kickoff(g))} MT</p><span class="badge ${a.kind}">${esc(a.label)}</span><h3>How you can watch</h3><p>${esc(a.line)}</p><p class="muted">${esc(a.detail)}</p><h3>Verification</h3><p class="muted">${g.verifiedAt?'Last checked '+esc(mountain(g.verifiedAt,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}))+' MT. Assignments expire after two hours.':'Local assignment has not been verified. A national CBS or FOX listing does not identify the Denver game.'}</p>${sourceLinks(g.sources)}${commonSources(g)}<p class="fine">RedZone is live coverage of selected moments, never an entitlement to a full out-of-market game. NFL+ full replays are available after games, not live TV access.</p>`);}}
function sourceLinks(s=[]){return `<div class="source-links">${s.filter(s=>safeUrl(s.url)).map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.title)} ${icon('arrow-up-right')}</a>`).join('')}</div>`;}
function commonSources(g){return sourceLinks([{title:'NFL official schedule',url:'https://www.nfl.com/schedules/'},{title:'506 Sports · regional broadcast maps',url:g?.season&&g?.week?`https://506sports.com/nfl.php?yr=${g.season}&wk=${g.week}`:'https://506sports.com/nfl/'},{title:'NFL+ device and casting restrictions',url:'https://support.nfl.com/hc/en-us/articles/35869809347860-Is-there-any-difference-between-NFL-on-my-mobile-app-NFL-on-my-computer-and-NFL-on-my-television'}]);}
function sourcesDialog(){modal('Sources & verification',`<p>Kickoffs and broadcaster listings come from ESPN’s current schedule feed. Denver channel assignments are matched to dated station listings refreshed by GitHub Actions, without a paid API key.</p><p class="muted">Each confirmed local assignment includes its source and original check time. Updates run about every 30 minutes. Missing evidence or data older than two hours stays unconfirmed. Streaming-rights exceptions require the linked official sources.</p>${commonSources(games[0])}${sourceLinks([{title:'Denver Broncos · how to watch',url:'https://www.denverbroncos.com/watch-live-games/ways-to-watch'},{title:'Denver7 / ABC',url:'https://www.denver7.com/'},{title:'9NEWS / NBC',url:'https://www.9news.com/'},{title:'FOX31',url:'https://kdvr.com/'},{title:'CBS Colorado',url:'https://www.cbsnews.com/colorado/'}])}`);}
async function reminders(){const sub=registration?await registration.pushManager.getSubscription():null;modal('Be there for kickoff.',`<div class="reminder-hero">${icon('bell-ring')}</div><p>Get a reminder about 15 minutes before your saved games, plus alerts when their kickoff or viewing options change.</p><p class="muted">${sub?'Reminders are enabled on this device.':api?'Enable notifications on this device to get started.':'Connect your live guide service in Settings to enable background notifications. Calendar reminders work without it.'}</p><p class="fine">${saved.length} saved game${saved.length===1?'':'s'}. Android may delay notifications in battery-saving mode. Uninstalling the app does not automatically delete a server subscription; use Turn off reminders first.</p><div class="modal-actions"><button class="button primary" id="enable-alerts" ${!api||!registration?'disabled':''}>${sub?'Sync saved games':'Enable notifications'}</button>${sub?'<button class="button" id="disable-alerts">Turn off reminders</button>':''}<button class="button" id="reminder-settings">Settings</button></div>`);$('#reminder-settings').onclick=settings;$('#enable-alerts').onclick=async()=>{try{if(!('PushManager'in window)||!('Notification'in window))throw new Error('Use Chrome on Android for background notifications.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notifications are blocked. Allow them in your browser’s site settings.');const c=await json(api+'/push-config');let current=await registration.pushManager.getSubscription();if(!current)current=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(atob(c.publicKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))});await syncSubscription(current);toast('Notifications enabled. Save games to get kickoff reminders.');reminders();}catch(e){toast(e.message);}};if(sub)$('#disable-alerts').onclick=async()=>{try{await json(api+'/subscription',{method:'DELETE',headers:{'Content-Type':'application/json','Authorization':'Bearer '+read('huddle.deviceToken','')},body:JSON.stringify({endpoint:sub.endpoint})});await sub.unsubscribe();toast('Reminders disabled and subscription removed.');reminders();}catch{toast('Could not remove the subscription. Reconnect and try again.');}};}
async function syncSubscription(sub){if(!api||!registration)return;sub=sub||await registration.pushManager.getSubscription();if(!sub)return;let token=read('huddle.deviceToken','');if(!token){token=crypto.randomUUID()+crypto.randomUUID();write('huddle.deviceToken',token);}await json(api+'/subscription',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({subscription:sub.toJSON(),saved,services})});}
async function install(){if(installPrompt){await installPrompt.prompt();installPrompt=null;}else{modal('Take Huddle to game day.',`<p>On Android, open this site in Chrome. Tap the browser menu, then <strong>Install app</strong> or <strong>Add to Home screen</strong>.</p><p class="muted">Once installed, open Game reminders to allow notifications. The guide’s companion service must be connected for background alerts.</p><p class="fine">An HTTPS connection is required. Offline mode shows your last loaded schedule with a saved-data label.</p>`);}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
shell();
try{const config=await json('./config.json');api=read('huddle.api',null)??config.apiUrl??'';if(api&&!safeUrl(api))api='';}catch{api=read('huddle.api','');}
if('serviceWorker'in navigator){try{registration=await navigator.serviceWorker.register(new URL('./sw.js',window.location.href));await navigator.serviceWorker.ready;}catch{}}
const unregisterTools=registerGuideTools(document.modelContext,()=>({dataState,checkedAt:checked,verificationMessage:verificationError,filter,team:query,games:games.map(g=>({id:g.id,matchup:g.away.name+' at '+g.home.name,date:g.date,kickoffMT:kickoff(g),networks:g.networks,access:access(g,services),sources:g.sources,verifiedAt:g.verifiedAt}))}),(f,q)=>{filter=f;query=q;$('#search').value=q;renderGames();});
window.addEventListener('pagehide',e=>{if(!e.persisted)unregisterTools();});
syncSubscription().catch(()=>{});
load();setInterval(()=>{if(!document.hidden&&!loading)load();},5*60e3);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!loading)load();});window.addEventListener('online',()=>load());

